version: '3'
services:
  db:
    image: postgres:15
    container_name: postgres-db-backendDeBase
    restart: always
    environment:
      POSTGRES_DB: backendDeBase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
